### ISSUE TITLE
Create Sign Up base form

### ISSUE THREAD

**Issue by ecruz17** [BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-1#2]
```[tasklist]
### Tasks
- [ ] Create input component for signup form
- [ ] Create button component
- [ ] Create checkboxes
- [ ] Create loading alert
```

![imagen](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-1/assets/47923715/03138e9b-1fd7-4a67-b628-e3a7ccc7aee2)
