### ISSUE TITLE
Create Login Screen

### ISSUE THREAD

**Issue by ShadowEnchanter** [BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-1#7]
### Tasks
- [x] Create Screen Component.
- [x] Link Sign-Up Screen to Login Screen.
- [x] Place Components to Login Screen.

![Login Screen Design](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-1/assets/47923715/ae097bef-ee2f-40d9-9022-18195f911abe)
