### ISSUE TITLE
 Connect to Firebase 

### ISSUE THREAD

**Issue by ShadowEnchanter** [BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-1#8]
### Tasks
- [x] Connect to Firebase in Project
- [x] Create User Login Validation
- [x] Create User SignUp
